### ISSUE TITLE
improve store/shard implementation

### ISSUE THREAD

**Issue by 0x77dev** [dstack-js/dstack#26]
- [ ] add the possibility to pin shard on a relay
- [ ] add the possibility to snapshot store data
- [ ] add the possibility to revoke store keys
- [ ] add the possibility to sign shards
- [ ] add the possibility to sign store keys
