### ISSUE TITLE
v0.3.0

### ISSUE THREAD

**Issue by 0x77dev** [dstack-js/dstack#90]
- [x] Move from IPFS to own implementation based on js-libp2p@next
 - This allows to achieve more customization and reduce bundle sizes
 - More flexibility in networking configuration
- [ ]  Data exchange layer
 - IPFS provides a stack for data sharing along with some techniques to store and distribute because IPFS removal it is needed to be partially implemented
- [x] ~~New Relay and Transport~~
 - ~~Relay and Transport need to be reimplemented~~
 - _Native libp2p transports will be used_
- [x] Move to ESM (with CommonJS support, achieved by using [microbundle](https://github.com/developit/microbundle#modern))
